### ISSUE TITLE
IMPROVEMENT quiz layout changes when the answer is given

### ISSUE THREAD

**Issue by maria-grozova** [md-ash-dot/classical-music-hackathon#200]
the answer button, progress bar and mute button drop down each time the correct/incorrect answer is shown. 
this result should be given min height to keep the layout consistent for a better user experience![Image](https://github.com/user-attachments/assets/a5bb8910-e396-4b14-9368-6d2d451111de)

**Comment by md-ash-dot** [comment]
The team has decided not to change this due to time constraints
